In [17]:
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [18]:
# SELECCIÓN DEL MODELO Y ENTRENAMIENTO

# Lectura del dataset

dataset = pd.read_csv('C:/Users/toled/OneDrive/Documentos/MATEMÁTICAS/TFG/Dataset NBA.csv',sep=";", encoding="ISO 8859-1")
dataset = dataset.drop('YEAR', 1)
dataset = dataset.drop('Team', 1)
dataset = dataset.drop('Arena', 1)
dataset = dataset.drop('Champion', 1)
dataset = dataset.drop('Attend.', 1)
dataset = dataset.drop('L%', 1)
dataset = dataset.drop('PW', 1)
dataset = dataset.drop('PL', 1)

dataset.head()

C:\Users\toled\AppData\Local\Temp/ipykernel_3208/1573650165.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dataset = dataset.drop('YEAR', 1)
C:\Users\toled\AppData\Local\Temp/ipykernel_3208/1573650165.py:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dataset = dataset.drop('Team', 1)
C:\Users\toled\AppData\Local\Temp/ipykernel_3208/1573650165.py:8: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dataset = dataset.drop('Arena', 1)
C:\Users\toled\AppData\Local\Temp/ipykernel_3208/1573650165.py:9: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  dataset = dataset.drop('Champion', 1)
C:\Users\toled\AppData\Local\Temp/ipykernel_3208/1573650165.py:

G     MP    FG   FGA   FG%    3P   3PA   3P%    2P   2PA  ...  3PAr   TS%  \
0  82  240.3  41.5  88.3  47.0  12.9  34.4  37.4  28.6  53.9  ...   390  58.1   
1  82  240.6  41.7  85.6  48.7   1.5   5.0  30.2  40.2  80.6  ...    59  54.7   
2  82  242.7  42.6  91.2  46.7   2.6   8.2  31.3  40.0  83.0  ...    90  51.9   
3  82  242.7  34.9  78.5  44.4   4.9  13.9  35.2  30.0  64.5  ...   177  52.7   
4  82  242.1  42.0  86.8  48.4   0.9   2.9  31.1  41.1  84.0  ...    33  53.6   

   OFeFG%  OfTOV%  ORB%  Of FT/FGA  DEFeFG%  DefTOV%  DRB%  Def FT/FGA  
0    54.3    10.8  23.0        205     54.3     11.5  76.9         177  
1    49.6    13.5  36.3        277     50.9     14.0  65.5         254  
2    48.1    13.0  33.6        203     49.7     13.2  68.3         209  
3    47.6    15.7  27.9        248     46.9     12.1  70.4         222  
4    48.9    15.3  32.5        250     48.5     15.2  63.8         249  

[5 rows x 42 columns]

In [19]:
# Preprocesado

# Se separa la columna a predecir
X = dataset.iloc[:,34:42]
y = dataset.iloc[:,25]


# En este ejemplo, se reescalan con un MinMaxScaler
sc = MinMaxScaler()
sc.fit(X) # Se ajusta el reescalador
X = sc.transform(X)

print(X)

[[0.78807947 0.10227273 0.24056604 ... 0.13793103 0.76616915 0.10526316]
 [0.47682119 0.40909091 0.86792453 ... 0.42528736 0.19900498 0.51052632]
 [0.37748344 0.35227273 0.74056604 ... 0.33333333 0.33830846 0.27368421]
 ...
 [0.39735099 0.32954545 0.54716981 ... 0.55172414 0.46766169 0.52105263]
 [0.44370861 0.30681818 0.48113208 ... 0.47126437 0.47263682 0.48421053]
 [0.70860927 0.27272727 0.16037736 ... 0.25287356 0.80099502 0.31578947]]


In [20]:
# Dividir el dataset en train y test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [24]:
# Create linear regression object
reg = LinearRegression()

# Train the model using the training sets
reg.fit(X_train,y_train)

# Make predictions using the testing set
y_pred = reg.predict(X_test)

# The coefficients
print("Coefficients: \n", reg.coef_)
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))


Coefficients: 
 [ 0.68756842 -0.38819115  0.27480942  0.18878591 -0.64369786  0.35405554
  0.22895119 -0.20652923]
Coefficient of determination: 0.93
